backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "projetos"
    label: "Projetos"
    label_singular: "Projeto"
    folder: "content/projetos"
    create: true
    slug: "{{slug}}"
    summary: "{{title}} - {{client}}"
    sortable_fields: ["title", "year"]
    preview_path: "portfolio.html"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição do Projeto", name: "description", widget: "text" }
      - { label: "Cliente", name: "client", widget: "string" }
      - { label: "Ano", name: "year", widget: "string" }
      - { label: "Categoria", name: "category", widget: "select", options: ["Branding", "Web Design", "Campanha", "Social Media"] }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Imagem de Capa", name: "image", widget: "image" }
      - label: "SEO"
        name: "seo"
        widget: "object"
        collapsed: true
        fields:
          - { label: "Título SEO", name: "seo_title", widget: "string", required: false }
          - { label: "Descrição SEO", name: "seo_description", widget: "text", required: false }
          - { label: "Imagem SEO", name: "seo_image", widget: "image", required: false }

  - name: "sobre"
    label: "Sobre Mim"
    files:
      - label: "Conteúdo"
        name: "sobre"
        file: "content/sobre.md"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Subtítulo", name: "subtitle", widget: "string" }
          - { label: "Texto", name: "body", widget: "markdown" }
          - { label: "Imagem de Perfil", name: "image", widget: "image" }

  - name: "home"
    label: "Página Inicial"
    files:
      - label: "Hero"
        name: "hero"
        file: "content/home/hero.md"
        fields:
          - { label: "Nome", name: "nome", widget: "string" }
          - { label: "Sobrenome", name: "sobrenome", widget: "string" }
          - { label: "Frase", name: "subtitle", widget: "string" }

  - name: "contato"
    label: "Seção Contato"
    files:
      - label: "Texto de Contato"
        name: "contact"
        file: "content/contact.md"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "string" }